#!/usr/bin/env ruby

require 'sometimes'

require 'shellwords'

require 'optparse'

# TODO check if tools are present

optparse, options = Sometimes::CLI::Common.option_parser
optparse.parse!

definition = Sometimes::read_def options[:conf_file]
key_path = File.expand_path definition.key

shescape = lambda {|v| Shellwords.escape v}
command = "ssh-keygen -q -N '' -C '%s' -f %s" % [definition.comment,
                                                 key_path].map(&shescape)

# Create the key-pair
Sometimes::Shell.execute(command)
if $?.exitstatus != 0
  STDERR.puts "Key creation failed!"
  exit 1
end

# Create authorized_keys file entry
what_path = File.expand_path definition.what
pub_key   = File.read(key_path + ".pub")
authorized_keys = Sometimes::AuthorizedKeysFile.line definition

# TODO sanity check, result check
File.open(key_path + ".authorized_keys.command", 'w') {|f| f.write(authorized_keys) }

# Explicit, graceful exit
exit 0
