#!/usr/bin/env ruby

require 'sometimes'

require 'optparse'

optparse, options = Sometimes::CLI::Common.option_parser
optparse.parse!

definition = Sometimes.read_def(options[:conf_file])

Sometimes::FileEnvironment.prepare! definition

# list contents (tree-like)
Sometimes::Shell.execute("tree -h #{definition.path}")

# Exit gracefully
exit 0
