#!/usr/bin/env ruby

require 'sometimes'

require 'shellwords'

optparse, options = Sometimes::CLI::Common.option_parser ""\
  "Create three files:\n"\
  "  - a keypair (public and private key)\n"\
  "  - a file containing a line for an authorized_keys file\n"\
  "The files are put in the location given by the defition file"
optparse.parse!

Sometimes::EnvironmentCheck.check!

definition = Sometimes::CLI::Common.load_definition options
key_path   = File.expand_path definition.key

shescape = lambda {|v| Shellwords.escape v}
command = "ssh-keygen -q -N '' -C '%s' -f %s" % [definition.comment,
                                                 key_path].map(&shescape)

# Create the key-pair
Sometimes::Shell.execute(command)
if $?.exitstatus != 0
  STDERR.puts "Key creation failed with exit #{$?.exitstatus}."
  exit 1
end

# Create authorized_keys file entry
what_path = File.expand_path definition.what
pub_key   = File.read(key_path + ".pub")
authorized_keys = Sometimes::AuthorizedKeysFile.line definition

# TODO sanity check, result check
File.open(key_path + ".authorized_keys.command", 'w') {|f| f.write(authorized_keys) }

# Explicit, graceful exit
exit 0
