#!/usr/bin/env ruby

require 'sometimes'

optparse, options = Sometimes::CLI::Common.option_parser
optparse.parse!

Sometimes::EnvironmentCheck.check!

definition = Sometimes::CLI::Common.load_definition options

Sometimes::FileEnvironment.prepare! definition

# list contents (tree-like)
puts ""
puts "Backups found:"
Sometimes::Shell.execute("tree -h #{definition.path}")

# list contents of last tgz (if its tgz)
puts ""
puts "Content of last backup:"
if definition.type.to_s == "tgz"
  Sometimes::Shell.execute("tar --list -f #{Sometimes::FileEnvironment.path_to_last_file definition}")
end

# Exit gracefully
exit 0
