#!/usr/bin/env ruby

require 'sometimes'

require 'optparse'
require 'date'

optparse, options = Sometimes::CLI::Common.option_parser
optparse.parse!

definition = Sometimes.read_def(options[:conf_file])

now = DateTime.now

# Pseudo-schedule (TODO)
if now.day == 1
  scheme = :monthly
elsif now.wday == 0 # sunday
  scheme = :weekly
else
  scheme = :daily
end

Sometimes::StoreCleaner.clean! definition, scheme

store_path = "#{definition.path}/#{scheme.to_s}"
file_extension = definition.type == 'mysql' ? 'sql' : 'tgz'
now_relpath = "#{store_path}/#{now.strftime('%F_%H%M')}.#{file_extension}"

ssh_command = "ssh -i #{definition.key} #{definition.user}@#{definition.host} > #{now_relpath}"
Sometimes::Shell.execute(ssh_command)

# Link it. TODO: Absolute paths
last_file_link_path = "#{definition.path}/last.#{file_extension}"
Sometimes::Shell.execute("rm #{last_file_link_path}")
Sometimes::Shell.execute("ln -s #{now_relpath} #{last_file_link_path}")

exit 0
