#!/usr/bin/env ruby

require 'sometimes'

require 'date'

optparse, options = Sometimes::CLI::Common.option_parser ""\
  "Runs a backup and shuffles files around as indicated by the definition file."
optparse.parse!

Sometimes::EnvironmentCheck.check!

definition = Sometimes::CLI::Common.load_definition options
Sometimes::FileEnvironment.prepare! definition

now = DateTime.now

# Pseudo-schedule (TODO)
if now.day == 1
  scheme = :monthly
elsif now.wday == 0 # sunday
  scheme = :weekly
else
  scheme = :daily
end

Sometimes::StoreCleaner.clean! definition, scheme

now_relpath = BackupFiles.path_to_file_now definition, scheme

ssh_command = "ssh -i #{definition.key} #{definition.user}@#{definition.host} > #{now_relpath}"
Sometimes::Shell.execute(ssh_command)

# Link it. TODO: Absolute paths
Sometimes::BackupFiles.link_last! definition, now_relpath

# Exit gracefully
exit 0
